# Name of website
title: PAAR 2026

# Your name to show in the footer
author: PAAR 2026 organizers

description: 10th Workshop on Practical Aspects of Automated Reasoning

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
